#!/bin/sh

LUAROCKS_SYSCONFDIR='/usr/local/etc/luarocks' exec '/usr/local/opt/lua/bin/lua5.4' -e 'package.path="/Users/alecrospierski/.luarocks/share/lua/5.4/?.lua;/Users/alecrospierski/.luarocks/share/lua/5.4/?/init.lua;/usr/local/share/lua/5.4/?.lua;/usr/local/share/lua/5.4/?/init.lua;"..package.path;package.cpath="/Users/alecrospierski/.luarocks/lib/lua/5.4/?.so;/usr/local/lib/lua/5.4/?.so;"..package.cpath' $([ "$*" ] || echo -i) "$@"
